export type QuizQuestionBilingual = {
  id: number;
  questionEn: string;
  questionHi: string;
  optionsEn: string[];
  optionsHi: string[];
  correctIndex: number;
};

export const QUIZ_POOL: QuizQuestionBilingual[] = [
  {
    id: 1,
    questionEn: "What is the recommended chest compression rate per minute during CPR?",
    questionHi: "CPR के दौरान प्रति मिनट अनुशंसित सीने की संपीड़न (Chest Compression) दर क्या है?",
    optionsEn: ["60 - 80 compressions/min", "80 - 100 compressions/min", "100 - 120 compressions/min", "140 - 160 compressions/min"],
    optionsHi: ["60 - 80 संपीड़न/मिनट", "80 - 100 संपीड़न/मिनट", "100 - 120 संपीड़न/मिनट", "140 - 160 संपीड़न/मिनट"],
    correctIndex: 2,
  },
  {
    id: 2,
    questionEn: "What is the correct compression-to-breath ratio for adult CPR?",
    questionHi: "वयस्क CPR के लिए सही संपीड़न-से-सांस (Compression-to-Breath) अनुपात क्या है?",
    optionsEn: ["15 compressions to 2 breaths", "30 compressions to 2 breaths", "50 compressions to 2 breaths", "10 compressions to 1 breath"],
    optionsHi: ["15 संपीड़न और 2 सांसें", "30 संपीड़न और 2 सांसें", "50 संपीड़न और 2 सांसें", "10 संपीड़न और 1 सांस"],
    correctIndex: 1,
  },
  {
    id: 3,
    questionEn: "Where should you place your hands when performing chest compressions on an adult?",
    questionHi: "वयस्क पर सीने का संपीड़न करते समय आपको अपने हाथ कहां रखने चाहिए?",
    optionsEn: ["On the upper abdomen", "On the center of the chest (lower half of breastbone)", "On the left side of the ribcage", "Near the collarbone"],
    optionsHi: ["पेट के ऊपरी हिस्से पर", "छाती के केंद्र में (स्टर्नम के निचले आधे हिस्से पर)", "पसली के बाईं ओर", "कॉलरबोन के पास"],
    correctIndex: 1,
  },
  {
    id: 4,
    questionEn: "What is the first step when witnessing an adult suddenly collapse?",
    questionHi: "किसी वयस्क को अचानक गिरते हुए देखने पर पहला कदम क्या होना चाहिए?",
    optionsEn: ["Start chest compressions immediately", "Check responsiveness and call for emergency help (108 / 112 / state specific emergency number)", "Give a glass of water", "Elevate the person's legs"],
    optionsHi: ["तुरंत छाती दबाना शुरू करें", "प्रतिक्रिया की जांच करें और आपातकालीन मदद (108 / 112 / राज्य विशिष्ट आपातकालीन नंबर) को कॉल करें", "एक गिलास पानी दें", "व्यक्ति के पैरों को ऊपर उठाएं"],
    correctIndex: 1,
  },
  {
    id: 5,
    questionEn: "What is the primary objective of performing CPR during cardiac arrest?",
    questionHi: "कार्डिएक अरेस्ट के दौरान CPR करने का मुख्य उद्देश्य क्या है?",
    optionsEn: ["To cure the underlying disease", "To maintain oxygenated blood flow to the brain and vital organs", "To restart the heart instantly without a defibrillator", "To check blood pressure"],
    optionsHi: ["मूल बीमारी का इलाज करना", "मस्तिष्क और महत्वपूर्ण अंगों में ऑक्सीजन युक्त रक्त प्रवाह बनाए रखना", "बिना डिब्रिलेटर के दिल को तुरंत चालू करना", "ब्लड प्रेशर चेक करना"],
    correctIndex: 1,
  },
  {
    id: 6,
    questionEn: "How deep should chest compressions be for an adult during CPR?",
    questionHi: "CPR के दौरान वयस्क के लिए छाती की संपीड़न गहराई कितनी होनी चाहिए?",
    optionsEn: ["1 inch (2.5 cm)", "At least 2 inches (5 cm) to maximum 2.4 inches (6 cm)", "4 inches (10 cm)", "0.5 inch (1 cm)"],
    optionsHi: ["1 इंच (2.5 सेमी)", "कम से कम 2 इंच (5 सेमी) से अधिकतम 2.4 इंच (6 सेमी)", "4 इंच (10 सेमी)", "0.5 इंच (1 सेमी)"],
    correctIndex: 1,
  },
  {
    id: 7,
    questionEn: "What does AED stand for in emergency cardiac care?",
    questionHi: "आपातकालीन कार्डियक देखभाल में AED का क्या अर्थ है?",
    optionsEn: ["Automated External Defibrillator", "Advanced Emergency Detector", "Automatic Energy Device", "Assisted Executive Defibrillator"],
    optionsHi: ["ऑटोमेटेड एक्सटर्नल डिफिब्रिलेटर (Automated External Defibrillator)", "एडवांस इमरजेंसी डिटैक्टर", "ऑटोमैटिक एनर्जी डिवाइस", "असिस्टेड एग्जीक्यूटिव डिफिब्रिलेटर"],
    correctIndex: 0,
  },
  {
    id: 8,
    questionEn: "What should you do if an AED becomes available while you are performing CPR?",
    questionHi: "यदि CPR करते समय AED उपलब्ध हो जाए तो आपको क्या करना चाहिए?",
    optionsEn: ["Finish 10 minutes of CPR first", "Turn on the AED immediately and follow its voice prompts", "Store it away until doctors arrive", "Shock the person manually without turning it on"],
    optionsHi: ["पहले 10 मिनट तक CPR पूरा करें", "तुरंत AED चालू करें और इसके वॉयस निर्देशों का पालन करें", "डॉक्टर आने तक इसे दूर रखें", "बिना चालू किए व्यक्ति को शॉक दें"],
    correctIndex: 1,
  },
  {
    id: 9,
    questionEn: "How do you check if an unresponsive victim is breathing normally?",
    questionHi: "आप कैसे जांचते हैं कि कोई बेहोश पीड़ित सामान्य रूप से सांस ले रहा है या नहीं?",
    optionsEn: ["Look for chest rise and listen for breathing for up to 10 seconds", "Shake the victim violently for 1 minute", "Place a mirror in front of nostrils for 30 seconds", "Check blood pressure"],
    optionsHi: ["10 सेकंड तक छाती का उठना देखें और सांस सुनें", "पीड़ित को 1 मिनट तक तेजी से हिलाएं", "30 सेकंड के लिए नथुने के सामने शीशा रखें", "ब्लड प्रेशर मापें"],
    correctIndex: 0,
  },
  {
    id: 10,
    questionEn: "If a person is gasping occasionally during cardiac arrest, is that normal breathing?",
    questionHi: "यदि कोई व्यक्ति कार्डिएक अरेस्ट के दौरान कभी-कभार हांफ (gasping) रहा है, तो क्या यह सामान्य सांस लेना है?",
    optionsEn: ["Yes, gasping means normal breathing", "No, gasping is agonal breathing and requires immediate CPR", "Yes, just wait for them to wake up", "Give them cough syrup"],
    optionsHi: ["हां, हांफना सामान्य सांस लेना है", "नहीं, हांफना (agonal breathing) कार्डिएक अरेस्ट का संकेत है और तुरंत CPR आवश्यक है", "हां, उनके जागने का इंतजार करें", "उन्हें कफ सिरप दें"],
    correctIndex: 1,
  },
  {
    id: 11,
    questionEn: "Why is complete chest recoil important after each compression?",
    questionHi: "प्रत्येक संपीड़न के बाद छाती का पूरी तरह वापस ऊपर उठना (recoil) क्यों महत्वपूर्ण है?",
    optionsEn: ["It cools down the skin", "It allows the heart to refill with blood between compressions", "It rests the rescuer's arms", "It prevents rib fractures"],
    optionsHi: ["यह त्वचा को ठंडा करता है", "यह संपीड़न के बीच दिल में दोबारा खून भरने की अनुमति देता है", "यह मददगार के हाथों को आराम देता है", "यह पसली टूटने से बचाता है"],
    correctIndex: 1,
  },
  {
    id: 12,
    questionEn: "What is the recommended method to open the airway of an unconscious victim without spinal injury?",
    questionHi: "बिना रीढ़ की हड्डी की चोट वाले बेहोश पीड़ित का वायुमार्ग खोलने की अनुशंसित विधि क्या है?",
    optionsEn: ["Head-tilt, chin-lift method", "Tongue pull method", "Neck twist method", "Jaw thrust method"],
    optionsHi: ["हेड-टिल्ट, चिन-लिफ्ट (Head-tilt, chin-lift) विधि", "जीभ खींचने की विधि", "गर्दन मोड़ने की विधि", "जॉ थ्रस्ट विधि (Jaw thrust method)"],
    correctIndex: 0,
  },
  {
    id: 13,
    questionEn: "When performing CPR on a child (1 year to puberty), how deep should chest compressions be?",
    questionHi: "बच्चे (1 वर्ष से किशोरावस्था तक) पर CPR करते समय छाती की संपीड़न गहराई कितनी होनी चाहिए?",
    optionsEn: ["About 2 inches (5 cm) or 1/3 depth of chest", "4 inches (10 cm)", "0.5 inch (1 cm)", "6 inches"],
    optionsHi: ["लगभग 2 इंच (5 सेमी) या छाती की गहराई का 1/3 हिस्सा", "4 इंच (10 सेमी)", "0.5 इंच (1 सेमी)", "6 इंच"],
    correctIndex: 0,
  },
  {
    id: 14,
    questionEn: "When giving breaths, how long should each breath last?",
    questionHi: "सांसें (breaths) देते समय, प्रत्येक सांस कितनी देर तक होनी चाहिए?",
    optionsEn: ["1 second, making the chest visibly rise", "5 seconds", "10 seconds", "30 seconds"],
    optionsHi: ["1 सेकंड, ताकि छाती स्पष्ट रूप से ऊपर उठे", "5 सेकंड", "10 सेकंड", "30 सेकंड"],
    correctIndex: 0,
  },
  {
    id: 15,
    questionEn: "What is Hands-Only CPR?",
    questionHi: "हैंड्स-ओनली (Hands-Only) CPR क्या है?",
    optionsEn: ["Continuous chest compressions without breaths for lay rescuers", "CPR performed using only fingers", "Giving breaths without compressions", "CPR done while lying down"],
    optionsHi: ["आम नागरिकों (lay rescuers) के लिए बिना सांसों के लगातार केवल छाती संपीड़न", "केवल उंगलियों से किया जाने वाला CPR", "बिना दबाए केवल सांसें देना", "लेटकर किया जाने वाला CPR"],
    correctIndex: 0,
  },
  {
    id: 16,
    questionEn: "If you are alone and witness an adult collapse, what should you do first before starting CPR?",
    questionHi: "यदि आप अकेले हैं और किसी वयस्क को गिरते हुए देखते हैं, तो CPR शुरू करने से पहले आपको सबसे पहले क्या करना चाहिए?",
    optionsEn: ["Call emergency services (108 / 112 / state specific emergency number) and get an AED if available", "Perform 10 minutes of CPR", "Check the victim's pockets", "Go home"],
    optionsHi: ["आपातकालीन सेवाओं (108 / 112 / राज्य विशिष्ट आपातकालीन नंबर) को कॉल करें और यदि उपलब्ध हो तो AED लाएं", "पहले 10 मिनट CPR करें", "पीड़ित की जेब चेक करें", "घर चले जाएं"],
    correctIndex: 0,
  },
  {
    id: 17,
    questionEn: "How many hands are typically used for chest compressions on an adult?",
    questionHi: "वयस्क के सीने के संपीड़न के लिए आमतौर पर कितने हाथों का उपयोग किया जाता है?",
    optionsEn: ["Two hands interlocked", "One finger", "One elbow", "Three hands"],
    optionsHi: ["दोनों हाथ एक दूसरे में लॉक करके", "एक उंगली", "एक कोहनी", "तीन हाथ"],
    correctIndex: 0,
  },
  {
    id: 18,
    questionEn: "What is the emergency helpline number for ambulance/medical emergencies in India?",
    questionHi: "भारत में एम्बुलेंस/चिकित्सा आपातस्थिति के लिए आपातकालीन हेल्पलाइन नंबर क्या है?",
    optionsEn: ["108 / 112 / state specific number", "100", "101", "139"],
    optionsHi: ["108 / 112 / राज्य विशिष्ट नंबर", "100", "101", "139"],
    correctIndex: 0,
  },
  {
    id: 19,
    questionEn: "Can bystander CPR double or triple a cardiac arrest victim's chances of survival?",
    questionHi: "क्या मौके पर मौजूद व्यक्ति द्वारा किया गया CPR कार्डिएक अरेस्ट पीड़ित के जीवित रहने की संभावना को दोगुना या तिगुना कर सकता है?",
    optionsEn: ["Yes, CPR significantly increases survival rates", "No, CPR has no effect", "No, CPR reduces survival", "Only if done by a surgeon"],
    optionsHi: ["हां, CPR जीवित रहने की दर में भारी वृद्धि करता है", "नहीं, CPR का कोई प्रभाव नहीं पड़ता", "नहीं, CPR संभावना कम करता है", "केवल सर्जन द्वारा किए जाने पर"],
    correctIndex: 0,
  },
  {
    id: 20,
    questionEn: "What should you do if the victim's chest does not rise during breathing?",
    questionHi: "यदि सांस देते समय पीड़ित की छाती ऊपर न उठे तो आपको क्या करना चाहिए?",
    optionsEn: ["Re-open the airway (head-tilt, chin-lift) and ensure a tight seal before the next breath", "Blow harder into stomach", "Stop CPR permanently", "Give chest compressions on the throat"],
    optionsHi: ["अगली सांस से पहले वायुमार्ग को फिर से खोलें (Head-tilt, chin-lift) और सही सील सुनिश्चित करें", "पेट में तेजी से हवा भरें", "CPR स्थायी रूप से बंद कर दें", "गले पर संपीड़न दें"],
    correctIndex: 0,
  },
  {
    id: 21,
    questionEn: "What is the correct hand placement for infant CPR (under 1 year)?",
    questionHi: "शिशु CPR (1 वर्ष से कम) के लिए सही हाथ की स्थिति क्या है?",
    optionsEn: ["2 fingers in the center of the chest, just below the nipple line", "Whole palm on stomach", "Two hands interlocked", "On the neck"],
    optionsHi: ["छाती के केंद्र में निप्पल लाइन के ठीक नीचे 2 उंगलियां", "पेट पर पूरी हथेली", "दोनों हाथ लॉक करके", "गर्दन पर"],
    correctIndex: 0,
  },
  {
    id: 22,
    questionEn: "What is the compression depth for an infant CPR?",
    questionHi: "शिशु CPR के लिए संपीड़न की गहराई कितनी होनी चाहिए?",
    optionsEn: ["About 1.5 inches (4 cm)", "3 inches (7.5 cm)", "5 inches (12 cm)", "0.1 inch"],
    optionsHi: ["लगभग 1.5 इंच (4 सेमी)", "3 इंच (7.5 सेमी)", "5 इंच (12 सेमी)", "0.1 इंच"],
    correctIndex: 0,
  },
  {
    id: 23,
    questionEn: "How often should rescuers switch roles during CPR to prevent fatigue?",
    questionHi: "थकावट से बचने के लिए मददगारों को CPR के दौरान कितनी बार भूमिकाएं बदलनी चाहिए?",
    optionsEn: ["Every 2 minutes (about 5 cycles of 30:2)", "Every 30 minutes", "Never switch", "Every 10 seconds"],
    optionsHi: ["हर 2 मिनट में (लगभग 30:2 के 5 चक्र के बाद)", "हर 30 मिनट में", "कभी न बदलें", "हर 10 सेकंड में"],
    correctIndex: 0,
  },
  {
    id: 24,
    questionEn: "What should you do if an adult is choking and conscious, but cannot breathe or talk?",
    questionHi: "यदि कोई वयस्क होश में है लेकिन दम घुट रहा है (Choking) और सांस या बात नहीं कर पा रहा है, तो आपको क्या करना चाहिए?",
    optionsEn: ["Perform abdominal thrusts (Heimlich maneuver)", "Offer a glass of water", "Pat lightly on shoulder", "Tell them to sleep"],
    optionsHi: ["पेट पर जोर से थ्रस्ट (Heimlich maneuver) दें", "एक गिलास पानी दें", "कंधे पर थपथपाएं", "उन्हें सोने के लिए कहें"],
    correctIndex: 0,
  },
  {
    id: 25,
    questionEn: "Where do you apply Heimlich maneuver abdominal thrusts on a choking adult?",
    questionHi: "दम घुट रहे वयस्क पर हेमलिच पैंतरा (Heimlich maneuver) कहां लागू किया जाता है?",
    optionsEn: ["Just above the navel (belly button) and below the ribcage", "On the lower abdomen", "On the throat", "On the lower back"],
    optionsHi: ["नाभि के ठीक ऊपर और पसलियों के नीचे", "पेट के सबसे निचले हिस्से पर", "गले पर", "पीठ के निचले हिस्से पर"],
    correctIndex: 0,
  },
  {
    id: 26,
    questionEn: "How should you help a choking infant (under 1 year) who cannot cry or breathe?",
    questionHi: "दम घुट रहे शिशु (1 वर्ष से कम) की मदद कैसे करनी चाहिए जो रो या सांस नहीं ले पा रहा?",
    optionsEn: ["5 back blows followed by 5 chest thrusts", "Abdominal thrusts like an adult", "Shake upside down by legs", "Give liquid medicine"],
    optionsHi: ["5 बैक ब्लो (पीठ पर थपकी) और फिर 5 चेस्ट थ्रस्ट", "वयस्क की तरह पेट दबाना", "पैरों से उल्टा लटकाकर हिलाना", "तरल दवा देना"],
    correctIndex: 0,
  },
  {
    id: 27,
    questionEn: "If a choking victim becomes unconscious, what should you do immediately?",
    questionHi: "यदि दम घुट रहा पीड़ित बेहोश हो जाता है, तो आपको तुरंत क्या करना चाहिए?",
    optionsEn: ["Lower them to the ground and start CPR compressions", "Run away", "Wait 15 minutes", "Try to stand them up"],
    optionsHi: ["उन्हें जमीन पर लिटाएं और CPR संपीड़न शुरू करें", "भाग जाएं", "15 मिनट इंतजार करें", "उन्हें खड़ा करने की कोशिश करें"],
    correctIndex: 0,
  },
  {
    id: 28,
    questionEn: "What is the Good Samaritan law concept regarding CPR assistance?",
    questionHi: "CPR सहायता के संबंध में गुड सेमरीटन (Good Samaritan) कानून की अवधारणा क्या है?",
    optionsEn: ["Protects bystanders who give emergency CPR in good faith from legal liability", "Mandates fines for rescuers", "Requires rescuers to pay medical bills", "Prohibits non-doctors from helping"],
    optionsHi: ["आपात स्थिति में नेक नीयत से मदद करने वाले नागरिकों को कानूनी उत्तरदायित्व से सुरक्षा प्रदान करता है", "मददगारों पर जुर्माना लगाता है", "मददगारों से मेडिकल बिल भरने की मांग करता है", "गैर-डॉक्टरों को मदद करने से रोकता है"],
    correctIndex: 0,
  },
  {
    id: 29,
    questionEn: "When AED pads are attached to a victim, what is the most important rule during analysis/shock?",
    questionHi: "जब AED पैड पीड़ित पर लगाए जाते हैं, तो विश्लेषण/शॉक के दौरान सबसे महत्वपूर्ण नियम क्या है?",
    optionsEn: ["Ensure NO ONE is touching the victim ('Stand Clear')", "Hold the victim's hands tightly", "Continue chest compressions during shock", "Pinch the victim's nose"],
    optionsHi: ["सुनिश्चित करें कि कोई भी पीड़ित को न छू रहा हो ('Stand Clear')", "पीड़ित के हाथों को कसकर पकड़ें", "शॉक के दौरान भी छाती दबाना जारी रखें", "पीड़ित की नाक बंद करें"],
    correctIndex: 0,
  },
  {
    id: 30,
    questionEn: "Where should AED pads be placed on an adult victim?",
    questionHi: "वयस्क पीड़ित पर AED पैड कहां लगाए जाने चाहिए?",
    optionsEn: ["Upper right chest below collarbone, and lower left side of chest", "Both on the stomach", "On both knees", "On the back and forehead"],
    optionsHi: ["कॉलरबोन के नीचे ऊपरी दाहिनी छाती, और छाती का निचला बायां हिस्सा", "दोनों पेट पर", "दोनों घुटनों पर", "पीठ और माथे पर"],
    correctIndex: 0,
  },
  {
    id: 31,
    questionEn: "What should you do if an adult victim is wet when using an AED?",
    questionHi: "यदि AED का उपयोग करते समय वयस्क पीड़ित गीला है तो आपको क्या करना चाहिए?",
    optionsEn: ["Wipe the chest dry before applying AED pads", "Do not use AED at all", "Submerge AED in water", "Apply pads directly on puddle"],
    optionsHi: ["AED पैड लगाने से पहले छाती को सुखाएं", "AED का बिल्कुल प्रयोग न करें", "AED को पानी में डुबोएं", "पानी के पोखर पर सीधे पैड लगाएं"],
    correctIndex: 0,
  },
  {
    id: 32,
    questionEn: "What should you do if the victim has a pacemaker implant visible under the skin where the AED pad goes?",
    questionHi: "यदि पीड़ित की त्वचा के नीचे पेसमेकर प्रत्यारोपण दिख रहा है, तो AED पैड कहां लगाना चाहिए?",
    optionsEn: ["Place AED pad at least 1 inch away from the implant site", "Place AED pad directly over the pacemaker", "Do not give CPR", "Remove the pacemaker"],
    optionsHi: ["AED पैड को पेसमेकर स्थान से कम से कम 1 इंच दूर रखें", "AED पैड सीधे पेसमेकर के ऊपर लगाएं", "CPR न दें", "पेसमेकर हटा दें"],
    correctIndex: 0,
  },
  {
    id: 33,
    questionEn: "When can you stop performing CPR on a victim?",
    questionHi: "आप पीड़ित पर CPR करना कब बंद कर सकते हैं?",
    optionsEn: ["When medical help (ambulance/doctor) arrives, or the victim starts breathing/moving, or you are physically exhausted", "After 1 minute", "When a crowd gathers", "After 5 compressions"],
    optionsHi: ["जब मेडिकल मदद आए, या पीड़ित सांस लेने/हिलने लगे, या आप शारीरिक रूप से पूरी तरह थक जाएं", "1 मिनट के बाद", "जब भीड़ जमा हो जाए", "5 संपीड़न के बाद"],
    correctIndex: 0,
  },
  {
    id: 34,
    questionEn: "What is the main sign of sudden cardiac arrest?",
    questionHi: "अचानक कार्डिएक अरेस्ट का मुख्य लक्षण क्या है?",
    optionsEn: ["Unresponsiveness and absence of normal breathing", "Severe headache only", "High fever", "Knee pain"],
    optionsHi: ["कोई प्रतिक्रिया न होना और सामान्य सांस का न होना", "केवल तेज सिरदर्द", "तेज बुखार", "घुटने का दर्द"],
    correctIndex: 0,
  },
  {
    id: 35,
    questionEn: "Is heart attack the exact same thing as cardiac arrest?",
    questionHi: "क्या हार्ट अटैक (Heart Attack) और कार्डिएक अरेस्ट (Cardiac Arrest) बिल्कुल एक ही चीज़ हैं?",
    optionsEn: ["No: Heart attack is a circulation problem (blocked artery); Cardiac arrest is an electrical failure causing the heart to stop beating", "Yes, they are identical terms", "Cardiac arrest only happens during sleep", "Heart attack means cardiac death instantly"],
    optionsHi: ["नहीं: हार्ट अटैक रक्त परिसंचरण की समस्या है; कार्डिएक अरेस्ट हृदय की धड़कन रुकने की विद्युत (electrical) विफलता है", "हां, वे बिल्कुल समान शब्द हैं", "कार्डिएक अरेस्ट केवल सोते समय होता है", "हार्ट अटैक का मतलब तुरंत मृत्यु है"],
    correctIndex: 0,
  },
  {
    id: 36,
    questionEn: "What should you do if an unresponsive cardiac arrest victim vomits during CPR?",
    questionHi: "यदि बेहोश कार्डिएक अरेस्ट पीड़ित को CPR के दौरान उल्टी हो जाए तो आपको क्या करना चाहिए?",
    optionsEn: ["Turn the victim to their side, clear the mouth/airway, turn back, and resume CPR", "Stop CPR and go away", "Force water down their throat", "Do nothing"],
    optionsHi: ["पीड़ित को करवट दिलाएं, मुंह/वायुमार्ग साफ करें, वापस सीधा करें और CPR शुरू करें", "CPR बंद करके चले जाएं", "उनके गले में पानी डालें", "कुछ न करें"],
    correctIndex: 0,
  },
  {
    id: 37,
    questionEn: "What is the Recovery Position?",
    questionHi: "रिकवरी पोजीशन (Recovery Position) क्या है?",
    optionsEn: ["Placing a breathing, unresponsive victim on their side to keep the airway clear", "Hanging upside down", "Sitting on a chair", "Standing against a wall"],
    optionsHi: ["सांस ले रहे बेहोश पीड़ित को वायुमार्ग खुला रखने के लिए करवट लिटाना", "उल्टा लटकाना", "कुर्सी पर बिठाना", "दीवार के सहारे खड़ा करना"],
    correctIndex: 0,
  },
  {
    id: 38,
    questionEn: "Why is early CPR and early defibrillation critical within the first 3-5 minutes of cardiac arrest?",
    questionHi: "कार्डिएक अरेस्ट के पहले 3-5 मिनट के भीतर शुरुआती CPR और डिफिब्रिलेशन क्यों महत्वपूर्ण है?",
    optionsEn: ["Brain damage starts within 4 minutes without oxygen; early action dramatically increases survival", "It reduces hospital fees", "It makes the victim sleep", "It cures fever"],
    optionsHi: ["ऑक्सीजन के बिना 4 मिनट में मस्तिष्क क्षति शुरू होती है; शुरुआती कार्रवाई जीवित रहने की संभावना बढ़ाती है", "यह अस्पताल की फीस कम करता है", "यह पीड़ित को सुलाता है", "यह बुखार ठीक करता है"],
    correctIndex: 0,
  },
  {
    id: 39,
    questionEn: "Can children or teenagers perform Hands-Only CPR in emergencies?",
    questionHi: "क्या बच्चे या किशोर आपात स्थिति में हैंड्स-ओनली CPR कर सकते हैं?",
    optionsEn: ["Yes, anyone trained can push hard and fast in the center of the chest to save a life", "No, only medical graduates are allowed", "No, it requires physical strength over 100 kg", "Only with written permission"],
    optionsHi: ["हां, प्रशिक्षित कोई भी व्यक्ति जान बचाने के लिए सीने के बीच में तेजी से दबा सकता है", "नहीं, केवल मेडिकल स्नातकों को अनुमति है", "नहीं, इसके लिए 100 किग्रा से अधिक ताकत की जरूरत है", "केवल लिखित अनुमति से"],
    correctIndex: 0,
  },
  {
    id: 40,
    questionEn: "What posture should a rescuer maintain while giving chest compressions?",
    questionHi: "छाती का संपीड़न करते समय मददगार को कौन सी मुद्रा (posture) रखनी चाहिए?",
    optionsEn: ["Kneel beside victim, elbows straight, shoulders directly over hands", "Sit far away with bent arms", "Stand on one leg", "Lie down beside victim"],
    optionsHi: ["पीड़ित के बगल में घुटने टेकें, कोहनियां सीधी रखें, कंधे हाथों के ठीक ऊपर हों", "मुड़ी हुई बाहों के साथ दूर बैठें", "एक पैर पर खड़े हों", "पीड़ित के पास लेट जाएं"],
    correctIndex: 0,
  },
  {
    id: 41,
    questionEn: "What is the role of an AED voice prompt?",
    questionHi: "AED वॉयस प्रॉम्प्ट (निर्देशों) की क्या भूमिका है?",
    optionsEn: ["Gives step-by-step spoken instructions on pad placement, analysis, and shock delivery", "Plays music to relax bystanders", "Calls 108 automatically", "Measures body height"],
    optionsHi: ["पैड लगाने, विश्लेषण करने और शॉक देने के बारे में चरण-दर-चरण मौखिक निर्देश देता है", "मददगारों को आराम देने के लिए संगीत बजाता है", "स्वचालित रूप से 108 को कॉल करता है", "शरीर की ऊंचाई मापता है"],
    correctIndex: 0,
  },
  {
    id: 42,
    questionEn: "If an AED prompt says 'No Shock Advised', what should you do next?",
    questionHi: "यदि AED निर्देश कहता है 'No Shock Advised' (शॉक की आवश्यकता नहीं है), तो आपको आगे क्या करना चाहिए?",
    optionsEn: ["Immediately resume chest compressions/CPR for 2 minutes until AED re-analyzes", "Turn off AED and leave", "Give water", "Throw away AED"],
    optionsHi: ["AED द्वारा पुनः विश्लेषण करने तक तुरंत 2 मिनट के लिए CPR संपीड़न फिर से शुरू करें", "AED बंद करके चले जाएं", "पानी दें", "AED फेंक दें"],
    correctIndex: 0,
  },
  {
    id: 43,
    questionEn: "What is the recommended surface to place a cardiac arrest victim on before starting CPR?",
    questionHi: "CPR शुरू करने से पहले कार्डिएक अरेस्ट पीड़ित को किस सतह पर लिटाने की सलाह दी जाती है?",
    optionsEn: ["A firm, flat surface (e.g. floor)", "A soft mattress", "A waterbed", "A swinging hammock"],
    optionsHi: ["एक सख्त, समतल सतह (जैसे फर्श)", "एक नरम गद्दे पर", "वाटरबेड पर", "झूलते झूले पर"],
    correctIndex: 0,
  },
  {
    id: 44,
    questionEn: "What is gasping in an unconscious person a sign of?",
    questionHi: "बेहोश व्यक्ति में हांफना (gasping) किस बात का संकेत है?",
    optionsEn: ["Cardiac arrest requiring immediate CPR", "Normal peaceful sleep", "Sneezing", "Yawning"],
    optionsHi: ["कार्डिएक अरेस्ट जिसके लिए तुरंत CPR की आवश्यकता होती है", "सामान्य शांतिपूर्ण नींद", "छींकना", "उबासी लेना"],
    correctIndex: 0,
  },
  {
    id: 45,
    questionEn: "Should you remove clothing from a victim's chest before applying AED pads?",
    questionHi: "क्या AED पैड लगाने से पहले पीड़ित की छाती से कपड़े हटाने चाहिए?",
    optionsEn: ["Yes, pads must adhere directly to bare skin", "No, place pads over heavy jackets", "No, place over leather belts", "Only if clothes are red"],
    optionsHi: ["हां, पैड सीधे नंगी त्वचा पर चिपकने चाहिए", "नहीं, भारी जैकेट के ऊपर रखें", "नहीं, बेल्ट के ऊपर रखें", "केवल अगर कपड़े लाल हों"],
    correctIndex: 0,
  },
  {
    id: 46,
    questionEn: "What is the main danger of delaying CPR during cardiac arrest?",
    questionHi: "कार्डिएक अरेस्ट के दौरान CPR में देरी करने का मुख्य खतरा क्या है?",
    optionsEn: ["Irreversible brain death within minutes due to lack of oxygenated blood", "Loss of hair", "Skin discoloration only", "Slight fever"],
    optionsHi: ["ऑक्सीजन युक्त रक्त की कमी से मिनटों में अपरिवर्तनीय मस्तिष्क मृत्यु (Brain Death)", "बालों का झड़ना", "केवल त्वचा की रंगत बदलना", "हल्का बुखार"],
    correctIndex: 0,
  },
  {
    id: 47,
    questionEn: "Can a non-medical citizen perform CPR correctly after watching an instructional module?",
    questionHi: "क्या कोई आम नागरिक निर्देश मॉड्यूल देखने के बाद सही ढंग से CPR कर सकता है?",
    optionsEn: ["Yes, CPR is a simple lifesaving skill that any aware citizen can perform", "No, requires 5 years of medical college", "No, forbidden by law", "Only doctors in uniform"],
    optionsHi: ["हां, CPR एक सरल जीवन रक्षक कौशल है जिसे कोई भी जागरूक नागरिक कर सकता है", "नहीं, 5 साल के मेडिकल कॉलेज की जरूरत है", "नहीं, कानून द्वारा वर्जित है", "केवल वर्दी में डॉक्टर"],
    correctIndex: 0,
  },
  {
    id: 48,
    questionEn: "What is the primary rhythm during cardiac arrest that an AED treats?",
    questionHi: "कार्डिएक अरेस्ट के दौरान प्राथमिक रिदम क्या है जिसका इलाज AED करता है?",
    optionsEn: ["Ventricular Fibrillation (VF) / Pulseless Ventricular Tachycardia", "Normal Sinus Rhythm", "Slow heart rate during sleep", "High blood pressure"],
    optionsHi: ["वेंट्रिकुलर फाइब्रिलेशन (VF) / पल्सलेस वент्रिकुलर टैचीकार्डिया", "सामान्य साइनस रिदम", "सोते समय धीमी गति", "उच्च रक्तचाप"],
    correctIndex: 0,
  },
  {
    id: 49,
    questionEn: "What should you tell bystanders when calling emergency services (108 / 112 / state specific number)?",
    questionHi: "आपातकालीन सेवाओं (108 / 112 / राज्य विशिष्ट नंबर) को कॉल करते समय आपको सहयोगियों को क्या बताना चाहिए?",
    optionsEn: ["Exact location, victim's unresponsiveness/breathing status, and that CPR is being performed", "Your favorite movie", "Weather forecast", "Ask for food delivery"],
    optionsHi: ["सटीक स्थान, पीड़ित की बेहोशी/सांस की स्थिति, और यह कि CPR किया जा रहा है", "अपनी पसंदीदा फिल्म", "मौसम का पूर्वानुमान", "खाना ऑर्डर करना"],
    correctIndex: 0,
  },
  {
    id: 50,
    questionEn: "What is the ultimate goal of the CPR Sanjeevani initiative by Indian Academy of Pediatrics?",
    questionHi: "इंडियन एकेडमी ऑफ पीडियाट्रिक्स द्वारा CPR संजीवनी पहल का अंतिम लक्ष्य क्या है?",
    optionsEn: ["To train and empower every citizen so that no life is lost due to lack of immediate CPR awareness", "To sell medical equipment", "To conduct sports events", "To promote TV shows"],
    optionsHi: ["हर नागरिक को प्रशिक्षित और सशक्त बनाना ताकि तत्काल CPR जागरूकता की कमी से किसी की जान न जाए", "चिकित्सा उपकरण बेचना", "खेल आयोजनों का संचालन करना", "टीवी शो का प्रचार करना"],
    correctIndex: 0,
  },
];

/**
 * Returns 5 randomly selected questions from the 50-question pool.
 * Option order is shuffled while maintaining the correct answer index.
 */
export function getRandomQuizQuestions(
  count: number = 5,
  lang: "english" | "hindi" = "english"
) {
  // Shuffle array using Fisher-Yates algorithm
  const shuffled = [...QUIZ_POOL].sort(() => 0.5 - Math.random());
  const selected = shuffled.slice(0, Math.min(count, QUIZ_POOL.length));

  return selected.map((q) => {
    const isHi = lang === "hindi";
    const rawOptions = isHi ? [...q.optionsHi] : [...q.optionsEn];
    const correctText = rawOptions[q.correctIndex];

    // Shuffle options so correct answer position varies randomly
    const shuffledOptions = [...rawOptions].sort(() => 0.5 - Math.random());
    const newCorrectIndex = shuffledOptions.indexOf(correctText);

    return {
      id: q.id,
      question: isHi ? q.questionHi : q.questionEn,
      options: shuffledOptions,
      correctIndex: newCorrectIndex,
    };
  });
}
